import { ANIM, TOKEN_SPRITE } from "../resources";
import { LevelData } from "./level.model";

export const LEVEL_DATA: Record<string, LevelData> = {
  "Level 1": {
    name: "Level 1",
    levelType: "puzzle",
    charMap: [
      "   www    ",
      "   wew    ",
      "   w.w    ",
      "   w.w    ",
      "   w.w    ",
      "   w.w    ",
      "   w.w    ",
      "   w.w    ",
      "   wxw    ",
      "   www    ",
    ],
    botFacing: "Down",
    nextLevel: "Level 2",
    tokenList: [
      "fwd",
      "fwd",
      "fwd3",
      "tr",
      "fwd",
      "fwd2",
      "fwd",
      "tl",
      "fwd4",
      "fwd",
      "fwd2",
      "tr",
      "fwd",
      "tl",
      "fwd3",
      "fwd",
      "tr",
      "fwd2",
      "fwd",
      "fwd4",
      "tl",
      "fwd",
      "fwd3",
      "tr",
      "fwd",
      "fwd2",
      "tl",
      "fwd",
      "fwd4",
      "tr",
      "fwd",
      "fwd2",
      "fwd3",
      "tl",
      "fwd",
      "tr",
      "fwd4",
      "fwd2",
      "fwd",
      "tl",
      "fwd3",
      "fwd",
      "tr",
      "fwd2",
      "fwd4",
      "fwd",
      "tl",
      "fwd3",
      "tr",
      "fwd2",
    ],
    numTokens: 6,
    instructionText: [
      "You will train baby bot 'Gippity'.",
      "He needs lots of help to find the exit!",
      "Guide him by selecting the falling",
      "Tokens in the right order and then",
      "select Execute Plan when ready.",
      "",
      "This is an early test level so it",
      "should not be too hard.",
    ],
    instructionIcon: TOKEN_SPRITE["fwd"],
    instructionIconText: "Forward Token",
  },
  "Level 2": {
    name: "Level 2",
    levelType: "puzzle",
    charMap: [
      "          ",
      "wwwwww    ",
      "wx...w    ",
      "wwww.w    ",
      "   w.w    ",
      "   w.w    ",
      "   wew    ",
      "   www    ",
      "          ",
      "          ",
    ],
    botFacing: "Up",
    nextLevel: "Level 3",
    tokenList: [
      "tr",
      "fwd",
      "fwd2",
      "tr",
      "tl",
      "fwd",
      "fwd",
      "tr",
      "fwd",
      "fwd2",
      "fwd",
      "tl",
      "fwd3",
      "fwd",
      "tr",
      "fwd2",
      "fwd4",
      "fwd",
      "tl",
      "fwd",
      "tr",
      "fwd2",
      "fwd",
      "tl",
      "fwd2",
      "fwd",
      "fwd3",
      "tr",
      "fwd",
      "fwd2",
      "tl",
      "fwd4",
      "fwd",
      "tr",
      "fwd3",
      "fwd",
      "tl",
      "fwd2",
      "fwd",
      "tr",
      "fwd4",
      "fwd",
      "fwd3",
      "tl",
      "fwd",
      "tr",
      "fwd2",
      "fwd",
      "fwd4",
      "fwd3",
    ],
    numTokens: 6,
    instructionText: [
      "That one was too easy, right? I think",
      "it's time to stop cutting corners!",
      "This level is not as 'straight forward'",
      "as the last one.  Hey... Gippity",
      "enjoys a good laugh now and then.",
    ],
    instructionIcon: TOKEN_SPRITE["tl"],
    instructionIconText: "Left Turn Token",
  },
  "Level 3": {
    name: "Level 3",
    levelType: "puzzle",
    charMap: [
      "          ",
      " wwwwww   ",
      " w....ww  ",
      " w...x.w  ",
      " w....ww  ",
      " w.wwww   ",
      " w....ww  ",
      " w...e.w  ",
      " w....ww  ",
      " wwwwww   ",
    ],
    botFacing: "Right",
    nextLevel: "Level 4",
    tokenList: [
      "tl",
      "bck",
      "bck2",
      "bck",
      "tr",
      "bck3",
      "bck",
      "bck2",
      "tl",
      "bck",
      "bck4",
      "tr",
      "bck",
      "bck2",
      "bck3",
      "bck",
      "tl",
      "bck2",
      "bck",
      "tr",
      "bck",
      "bck3",
      "tl",
      "bck2",
      "bck",
      "tr",
      "bck4",
      "bck",
      "bck2",
      "tl",
      "bck",
      "tr",
      "bck3",
      "bck",
      "tl",
      "bck4",
      "bck",
      "tr",
      "bck2",
      "bck3",
      "bck4",
      "tr",
      "bck",
      "tl",
      "bck2",
      "tr",
      "bck3",
      "bck4",
      "bck",
      "bck",
    ],
    numTokens: 10,
    instructionText: [
      "Gippity is getting a little confused",
      "and needs to backtrack his course.",
      "He has total faith in you, the USER,",
      "and doesn't even need to see where",
      "he's going.",
      "",
      "He just read the Moonwalk_Skill.md !",
    ],
    instructionIcon: TOKEN_SPRITE["bck"],
    instructionIconText: "Backward Token",
  },
  "Level 4": {
    name: "Level 4",
    levelType: "puzzle",
    charMap: [
      "          ",
      "wwwwwwwwww",
      "wx.......w",
      "wwwwww...w",
      "  w......w",
      "www......w",
      "w.....wwww",
      "we.w.zd.xw",
      "w..w..wwww",
      "wwwwwww   ",
    ],
    botFacing: "Right",
    nextLevel: "Level 5",
    tokenList: [
      "tr",
      "fwd",
      "fwd",
      "fwd",
      "tr",
      "tr",
      "fwd4",
      "tl",
      "pu",
      "fwd4",
      "fwd2",
      "tr",
      "fwd3",
      "fwd2",
      "fwd",
      "fwd4",
      "tr",
      "fwd",
      "pu",
      "fwd3",
      "tl",
      "fwd2",
      "tr",
      "tr",
      "fwd2",
      "fwd3",
      "use",
      "fwd3",
      "fwd2",
      "fwd",
      "fwd",
      "fwd3",
      "use",
      "tl",
      "fwd2",
      "fwd2",
      "fwd",
      "bck4",
      "fwd4",
      "fwd",
      "fwd3",
      "fwd4",
      "fwd",
      "fwd3",
      "tl",
      "fwd4",
      "bck",
      "tr",
      "use",
      "tl",
    ],
    numTokens: 18,
    instructionText: [
      "Uh oh!! It looks like Gippity is",
      "hallucinating again!!  He thinks",
      "he is going to find a key and be",
      "able to pick it up!  So silly.",
      "Don't worry, we protected the door",
      "so HE WILL learn to stop trying.",
      "Discretion is the better part of",
      "valor, right?",
    ],
    instructionIcon: ANIM["shockTile1"],
    instructionIconText: "Zappy Tower",
  },
  "Level 5": {
    name: "Level 5",
    levelType: "puzzle",
    charMap: [
      "          ",
      "wwwwwwwwww",
      "wx.....zzw",
      "w........w",
      "wzzzzzz..w",
      "w........w",
      "w..zzzzzzw",
      "wz.......w",
      "wz......ew",
      "wwwwwwwwww",
    ],
    botFacing: "Left",
    nextLevel: "Title",
    tokenList: [
      "tr",
      "fwd",
      "fwd",
      "fwd",
      "tr",
      "tr",
      "fwd4",
      "tl",
      "pu",
      "fwd4",
      "fwd2",
      "tr",
      "fwd3",
      "fwd2",
      "fwd",
      "fwd4",
      "tr",
      "fwd",
      "pu",
      "fwd3",
      "tl",
      "fwd2",
      "tr",
      "tr",
      "fwd2",
      "fwd3",
      "use",
      "fwd3",
      "fwd2",
      "fwd",
      "fwd",
      "fwd3",
      "use",
      "tl",
      "fwd2",
      "fwd2",
      "fwd",
      "bck4",
      "fwd4",
      "fwd",
      "fwd3",
      "fwd4",
      "fwd",
      "fwd3",
      "tl",
      "fwd4",
      "bck",
      "tr",
      "use",
      "tl",
    ],
    numTokens: 20,
    instructionText: [
      "Gippity hasn't learned his lesson",
      "so we have to step up the training.",
      "Luckily we just built a bunch of new",
      "power stations so we can FINALLY",
      "train him the PROPER way. With Love.",
      "No mistakes allowed here -- we did",
      "invent reinFORCEment learning,",
      "after all."
    ],
    instructionIcon: ANIM["shockTile1"],
    instructionIconText: "Zappy Tower",
  },
};

// // 10x10 level represented as rows of characters: 'w' = wall, '.' = floor
// export const LEVEL_TEMPLATE_TILES: string[] = [
//   'wwwwwwwwww',
//   'w........w',
//   'w........w',
//   'w........w',
//   'w........w',
//   'w........w',
//   'w........w',
//   'w........w',
//   'w........w',
//   'wwwwwwwwww',
// ];
